-- MySQL Script generated by MySQL Workbench
-- 09/19/17 22:55:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sev0.1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sev0.1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sev0.1` DEFAULT CHARACTER SET utf8 ;
USE `sev0.1` ;

-- -----------------------------------------------------
-- Table `sev0.1`.`docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sev0.1`.`docs` (
  `idDoc` INT(11) NOT NULL,
  `title` VARCHAR(1000) NOT NULL,
  `author` VARCHAR(1000) NOT NULL,
  `credits` VARCHAR(1000) NULL DEFAULT NULL,
  `abstract` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idDoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sev0.1`.`invertedindex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sev0.1`.`invertedindex` (
  `idDoc` INT(11) NOT NULL,
  `term` VARCHAR(100) NOT NULL,
  `tf` INT(11) NOT NULL,
  PRIMARY KEY (`idDoc`, `term`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sev0.1`.`query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sev0.1`.`query` (
  `term` VARCHAR(45) NOT NULL,
  `tf` INT(11) NOT NULL,
  PRIMARY KEY (`term`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sev0.1`.`terms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sev0.1`.`terms` (
  `term` VARCHAR(45) NOT NULL,
  `idf` DOUBLE NOT NULL,
  PRIMARY KEY (`term`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sev0.1`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sev0.1`.`test` (
  `id` INT(11) NOT NULL,
  `testNom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
